__dependency__: configs/dual-encoder.yaml, configs/LF-Wikipedia-500K/dataset.yaml
expname: dist-de-hnm_decoupled-softmax_exp
desc: "Training dist-de-hnm (distributed dual-encoder with hard negative mining) with decoupled-softmax loss"

# Network and loss parameters
net: dist-de-hnm
norm_embs: False
tau: 1
neg_type: shorty # sample negatives from shortlist
hard_neg_start: 5
hard_neg_topk: 100
num_neg_samples: 5

loss_criterion: decoupled-softmax
loss_sample: True

# Training parameters
bsz: 768
gc_bsz: 512
lr: 2.e-5
dropout: 0